image: node:latest

stages:
  - build
  - test

before_script:
  - cd proyecto-react

build:
  stage: build
  script:
    - npm install
    - npm run build
    - node build.js || sentry-cli send-event --auth-token $SENTRY_AUTH_TOKEN --dsn $SENTRY_DSN --message "Error de compilación"

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test
    - npm test || sentry-cli send-event --auth-token $SENTRY_AUTH_TOKEN --dsn $SENTRY_DSN --message "Error de prueba"
