image: node:latest

stages:
  - build
  - test

before_script:
  - cd proyecto-react
  - npm install -g @sentry/cli

build:
  stage: build
  script:
    - npm install
    - npm run build || sentry-cli send-event --auth-token $SENTRY_AUTH_TOKEN --dsn $SENTRY_DSN --message "Error de compilación"

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test || sentry-cli send-event --auth-token $SENTRY_AUTH_TOKEN --dsn $SENTRY_DSN --message "Error de prueba"

after_script:
  - VERSION=$(sentry-cli releases propose-version)
  - sentry-cli releases new "$VERSION" --project ale-aguiar-diaz/proyecto-react
  - sentry-cli releases set-commits "$VERSION" --auto --project ale-aguiar-diaz/proyecto-react
  - sentry-cli releases finalize "$VERSION" --project ale-aguiar-diaz/proyecto-react
