image: node:latest

stages:
  - build
  - test

variables:
#  VITE_SENTRY_DSN: "$VITE_SENTRY_DSN"
  VITE_QUOTE_API_URL: "$VITE_QUOTE_API_URL"
  VITE_WEATHER_API_URL: "$VITE_WEATHER_API_URL"
  VITE_QUOTE_API_KEY: "$VITE_QUOTE_API_KEY"
  VITE_WEATHER_API_KEY: "$VITE_WEATHER_API_KEY"

before_script:
  - cd proyecto-react
  # - npm install -g @sentry/cli
  # - sentry-cli login --auth-token $SENTRY_AUTH_TOKEN
  # - sentry-cli send-event -m "Conexión de prueba exitosa"

build:
  stage: build
  script:
    - npm install
    - npm run build || echo "Error de compilación"

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test || echo "Error en los tests"

#after_script:
  # - VERSION=$(sentry-cli releases propose-version)
  # - sentry-cli releases new "$VERSION"
  # - sentry-cli releases set-commits "$VERSION" --auto
  # - sentry-cli releases finalize "$VERSION"
